### ISSUE TITLE
Add "Glow-Up Bulb (Pre-Errata)"

### ISSUE THREAD

**Issue by curiosport** [ProjectIgnis/CardScripts#1031]
https://yugipedia.com/wiki/Card_Errata:Glow-Up_Bulb

What I ask is that you please add the original effect of the card "Glow-Up Bulb" so that I can use it in the puzzles.

Currently the card works with the "Second erratum":

> If this card is in your GY: You can send the top card of your Deck to the GY, **and if you do**, Special Summon this card. You can only use this effect of "Glow-Up Bulb" once per Duel.

What I ask is that you add the original version (in Pre-Errata folder):

> You can send the top card of your Deck to the Graveyard and Special Summon this card from the Graveyard. Each player can only use the effect of "Glow-Up Bulb" once per Duel.

This is the script, I have tested it and it works:
```
--グローアップ·バルブ
function c67441435.initial_effect(c)
	--spsummon
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(67441435,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetRange(LOCATION_GRAVE)
	e1:SetCountLimit(1,67441435+EFFECT_COUNT_CODE_DUEL)
	e1:SetTarget(c67441435.target)
	e1:SetOperation(c67441435.operation)
	c:RegisterEffect(e1)
end
function c67441435.target(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then return Duel.IsPlayerCanDiscardDeck(tp,1)
		and Duel.GetLocationCount(tp,LOCATION_MZONE)>0 and c:IsCanBeSpecialSummoned(e,0,tp,false,false) end
	Duel.SetOperationInfo(0,CATEGORY_DECKDES,nil,0,tp,1)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,c,1,0,0)
end
function c67441435.operation(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetFieldGroupCount(tp,LOCATION_DECK,0)==0 then return end
	Duel.DiscardDeck(tp,1,REASON_EFFECT)
	local c=e:GetHandler()
	if not c:IsRelateToEffect(e) then return end
	Duel.SpecialSummon(c,0,tp,tp,false,false,POS_FACEUP)
end

```

**Comment by pyrQ** [comment]
1) We don't do TCG-only "erratas".
2) I would hardly call this a functional errata considering that its first print was pre-PSCT and that text update was post-PSCT.
3) Although not as important as the previous 2 points, the script you provided doesn't follow our standards.

**Comment by curiosport** [comment]
How do I determine that?
> TCG-only "erratas"

**pre-PSCT**, do you mean that the version I propose is from before the 1st Edition?

And my proposal does not fit in any category of the game? Because I have a puzzle that uses that version of the card and it only works in older versions of ygopro, I was hoping to use it in modern versions.

When making this type of proposal is it mandatory to provide the script? I only did it because I had it, it was not programmed by me.
