### ISSUE TITLE
Simoon and Shamal Have identical effects but coding is different

### ISSUE THREAD

**Issue by SonGokuSpirit** [ProjectIgnis/CardScripts#1044]
Blackwing - Simoon the Poisonous Cloud and Blackwing - Shamal the Sandstorm have identical spell placement effects and yet it's Shamal that gives you a choice and then zone placement and Simoon goes straight into zone placement with no choice. Providing they are identical, can that part of the coding that gives it zone placement the same (Both get choices before zone placement or straight into zone placement with no choice)?

Many Thanks
Discord: son_gokus_spirit

**Comment by NaimSantos** [comment]
I did not tell you to open an issue here. I told you about the pull request because that is the way to have changes in the scripts added to the game. If you did not know how to do it you could've just have reported the situation in one of the bugs channel instead.
