### ISSUE TITLE
Feature request: 5 moves each turn

### ISSUE THREAD

**Issue by Sbatushe** [ProjectIgnis/CardScripts#1112]
I don't know if this is the correct place to send this request, but i would like to add a custom rule in EDOPro: with this rule, for each turn the current player can do only 5 moves (a move is a basic action: a summon, an effect activation or a card placement). The moves counter reset on each turn and, during opponent's turn, i have to use the moves which i haven't used in my turn.
I think this is a simple yet effective way to regulate the infinite turns problem which affect modern yugioh.
Currently, for-fun decks are completely unplayable, but this rule could fix it.

**Comment by NaimSantos** [comment]
We do not take request for custom rules
