### ISSUE TITLE
"Engraver of the Mark" lets you view opponent's deck when chained to their "Crossout Designator"

### ISSUE THREAD

**Issue by Archielotl** [ProjectIgnis/CardScripts#1120]
If the opponent uses Crossout Designator and you activate Engraver of the Mark to change the name they declared, you are only able to declare a card in their deck. Leaving the search bar empty lets you view the names of every card in their deck.

**Comment by NaimSantos** [comment]
As mentioned in the [README](https://github.com/ProjectIgnis/CardScripts/blob/master/README.md) file, reports should be sent via Discord, in the bugs channel, and not via github.
