### ISSUE TITLE
Unable to Access Discord

### ISSUE THREAD

**Issue by VDDragonRider** [ProjectIgnis/CardScripts#1140]
I realize this is probably not where I should place this issue, but I don't know where else to go. I have tried multiple times to access the discord server for ProjectIgnis from https://projectignis.github.io/, but each time the invite is invalid or unable to be accepted. Please provide any direction for me or make any updates necessary so I can join the server. Thank you.

**Comment by pyrQ** [comment]
Ask someone you know to open a modmail ticket in the Discord server.
