### ISSUE TITLE
Update the c420 token to remove IsFusionSetCard

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#122]
This script, that handles non-official archetypes, uses  **IsFusionSetCard**. Those should be changed, so only **IsSetCard** is used, but the changes must consider that additional parameters must be passed to the function if the card is being used for a fusion summon. Changing that also implies changing how the archetypes are called, to consider those parameters.

**Comment by kevinlul** [comment]
Probably resolved with #178
