### ISSUE TITLE
Making unaffected cards leave the field via effects

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#152]
Consider a card that makes others unaffected. Examples `Metamorformation + a Metalfoes monster` `Aquarium Stage + a Aquaactress monster`
If you attempt to return only the unaffected card to the hand by using an effect, you are unable to, which is correct. Now if you attempt to return both the unaffected card AND the card that makes it unaffected, you are able to, which is wrong. Reported first in Percy.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/0c5ac862668b558f397d74d9454349c9f1237ae0
