### ISSUE TITLE
Bujinki Ahashima

### ISSUE THREAD

**Issue by LogicalNonsense2051** [ProjectIgnis/CardScripts#156]
2, possibly 3 problems relating to this card.

* If the player selects a "Zoodiac" monster to special summon from hand/GY, then chooses to Xyz summon a "Zoodiac" Xyz monster, the game will give the player the choice of summoning the Xyz monster via the normal way or with the monster's alternative summoning method (and no materials will be under it if the latter is picked).

* The monster selected from hand is never special summoned.

* Allegedly, it was reported that if an Xyz monster activates its effect that does not detaches any material(s) (in this puzzle, "Number 90: Galaxy-Eyes Photon Lord"), then the S/T destruction effect of "Bujinki Ahashima" will still trigger. Have not tested this in Percy (no replay was provided either) and have not successfully reproduced this bug on EDOPro.

[Puzzle associated with this issue.](https://github.com/kevinlul/edopro-config/blob/master/puzzles/Folder%20-%20Tests%20for%20known%20bugs%20in%20Percy/Test%20156%20-%20Bujinki%20Ahashima.lua)

**Comment by kevinlul** [comment]
These seem to be resolved, likely by cb4efc34d6fce70edc56e2722ee90c68efea1cdd
