### ISSUE TITLE
Workflow: reverting a file to baseline state doesn't revert in the delta repo

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#172]
This is because the file counts as not modified and not deleted in the current history when compared with the base and with the last run. To fix I should probably compare everything with the last run only and assume the delta repo remains in a consistent state.

**Comment by pyrQ** [comment]
Should be fixed now: https://github.com/ProjectIgnis/CardScripts/commit/00f94eb81c022282ef026831fe4de5cf59586630
