### ISSUE TITLE
Deck Master Rework

### ISSUE THREAD

**Issue by ClementLouis** [ProjectIgnis/CardScripts#175]
The current Limitation (Deck Masters being "pendulum") are wrong on some points and create problem (impossible to use DM + pendulums)
With the addition of Skill and Last Will function, we can use an similar implementation to have something better that don't require overwriting ton of essentials functions
List of Deck Masters:

- [x] Blue-Eyes White Dragon
- [x] Total Defense Shogun
- [x] Deepsea Warrior
- [x] Kuriboh
- [x] Nightmare Penguin
- [x] Dark Magician Girl
- [x] Flame Swordman
- [x] Judge Man
- [x] Robotic Knight
- [x] Goddess with the Third Eyes
- [x] Strike Ninja
- [x] Super Roboyarou
- [x] Jinzo
- [x] Lord of D.
- [x] Dark Magician
- [x] Kaiser Sea Horse
- [x] Shinato's Ark
- [x] Shinato, King of a Higher Plane

**Comment by kevinlul** [comment]
Current implementation is likely buggy in many ways.

**Comment by pyrQ** [comment]
Updated here: https://github.com/ProjectIgnis/CardScripts/commit/f2b35907b8c1e058a7596c31dad49ebc9a26a716
