### ISSUE TITLE
Orichalcos Kyutora (Anime) Bug

### ISSUE THREAD

**Issue by uforgivent-edopro** [ProjectIgnis/CardScripts#177]
The Problem here appears when "Orichalcos Kyutora" is destroyed and summons "Orichalcos Shunoros", the latter does not gain the sum of all the damage that "Orichalcos Kyutora" absorbed before being destroyed.
PS: In another Duel, I have noticed that it only absorbs all damage from battles involving only "Orichalcos Kyutora" and only that amount is added to "Orichalcos Shunoros"
[Bug Orichalcos Kyutora (Anime).zip](https://github.com/ProjectIgnis/CardScripts/files/4471816/Bug.Orichalcos.Kyutora.Anime.zip)

**Comment by kevinlul** [comment]
> Send bug reports through Discord only!
> Bug reports go on Discord; do NOT open an issue or pull request if you're not one our contributors.
A second infraction will result in a ban.
