### ISSUE TITLE
Deprecated Lua math library functions

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#188]
> The following functions were deprecated in the mathematical library: atan2, cosh, sinh, tanh, pow, frexp, and ldexp. You can replace math.pow(x,y) with x^y; you can replace math.atan2 with math.atan, which now accepts one or two arguments; you can replace math.ldexp(x,exp) with x * 2.0^exp. For the other operations, you can either use an external library or implement them in Lua. 

Cards that use math.pow:
111215001
511001376
511027010
511027092
511310034
511600210

Requested by @pyrQ 09/04/2020

See also pull requests #173 #174

**Comment by AlphaKretin** [comment]
It's also worth noting that most uses of `math.pow` are a power of 2 that's better represented using a bitshift.

**Comment by NaimSantos** [comment]
Finished in https://github.com/ProjectIgnis/CardScripts/commit/806c9ace18343e82e4c3678bbdc4293b74023e7d
