### ISSUE TITLE
"Dark Spirit of the Silent" bug

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#192]
Community report 12/04/2020

> On turn 8 Dark Spirit of the Silent was used and the targeted monster didn't attack. I then tried to attack on turn 10 with the monster whose attack got negated and I was unable to attack with it.

[Replay](https://cdn.discordapp.com/attachments/184324960842416129/698769319324286996/Dark_Spirit_of_the_Silent.yrpX)

**Comment by NaimSantos** [comment]
Fixed in https://github.com/ProjectIgnis/CardScripts/commit/f44d8f166c04cd77dd9a895353181ae340812975
