### ISSUE TITLE
"Spellbook of the Master" fails to copy and apply "Spellbook of Power"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#194]
[Turn 2](https://cdn.discordapp.com/attachments/291708361752313866/697549826082209802/Master_bug.yrpX)

Reported 08/04/2020 by @NaimSantos

**Comment by NaimSantos** [comment]
Fixed in https://github.com/ProjectIgnis/CardScripts/commit/7f1befd90e9669da03afd7e88f5277156848cf46
