### ISSUE TITLE
"Judgment Arrows" area of effect

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#195]
> When there is 1 Judgment Arrows on each side of the field, one affects all monsters pointed by both (a Link Monster pointed by it battles, the ATK of ALL Link Monsters pointed by both double for that battle as well; one side's Judgment Arrows leaves the field, ALL monsters pointed by both are destroyed). Also, it's counted as a monster for effects like Armatos Legio Magnus Dux's Firewall one.

[Turn 3](https://cdn.discordapp.com/attachments/184324960842416129/696918001076928562/Judgment_Arrows_Turn_3.yrpX)

Community report 06/04/2020 noted by @ahtelel 

The second "counted as a monster" report is likely related to a general rework we need for cards using `GetLinkedGroup` to additionally filter for monsters if that is what their Japanese card text says. See #107 and #79

**Comment by NaimSantos** [comment]
Part 2 was fixed in https://github.com/ProjectIgnis/CardScripts/commit/e74136be8972e935ed99e2396261c4d9253f1791

**Comment by NaimSantos** [comment]
Fixed in https://github.com/ProjectIgnis/CardScripts/commit/5b50de49b5b2eceaf60a6c291b4d19db5456c52e
