### ISSUE TITLE
"House Duston" apparently ignores the single control clause

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#196]
Reported 08/03/2020

**Comment by NaimSantos** [comment]
I don't understand what this mean. Is House Duston allowing to select a "Duston" monster that you already control? Is it allowing you to select 2 of the same duston to summon to your field?

**Comment by kevinlul** [comment]
![image](https://cdn.discordapp.com/attachments/586821870070792223/686421882630832183/Screen_Shot_2020-03-08_at_10.54.35_PM.png)
