### ISSUE TITLE
Ending the Battle Phase with "Electromagnetic Turtle" prevents the destruction of "Magical Hats" monsters

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#197]
Rulings question for @pyrQ before classifying this as a bug

[Turn 9](https://cdn.discordapp.com/attachments/291708361752313866/696564240387145728/Magical_Hats_-_Turn_9.yrpX)

Noted 05/04/2020 by @ahtelel

**Comment by pyrQ** [comment]
Fixed with this update:
https://github.com/ProjectIgnis/CardScripts/commit/0f69fbe9633139c8827cd61558a32c35f4f57a82
