### ISSUE TITLE
ATK change interactions: going back to "normal"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#198]
- Apollousa equipped with Moon Mirror Shield does not change ATK during damage calculation, when it should change according to Moon Mirror Shield and go back to normal after. [Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/682212841532686336/ApollousaMoon.lua)

- Utopia summoned by Utopia Double returns to 2500 ATK after Double or Nothing instead of 5000 ATK. [Ruling](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12787&keyword=&tag=-1&request_locale=ja) [Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/682213008356802580/UtopiaDouble.lua)

Reported 26/02/2020 by @lrhel

**Comment by edo9300** [comment]
Those interactions seem to work fine now

**Comment by kevinlul** [comment]
Only the second interaction regarding Utopia is fixed.

**Comment by kevinlul** [comment]
My apologies, the interaction is correct now, just that Red Gadget would happen to not cause an ATK change because it has 1500 DEF to a 1600 ATK Apollousa.
