### ISSUE TITLE
"Abyss Actor - Curtain Raiser" summonable under "Heat Wave"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#199]
The following interaction happens in game but is incorrect.

> You can activate the Pendulum Effect of something like Abyss Actor - Curtain Raiser while the effect of Heat Wave is applying. (The Pendulum Monster is a Spell at the time so IsCanBeSpecialSummoned returns true?)

> Not sure if it's better to have Heat Wave also check for the original type, or to edit the Pendulum Monsters somehow, or a different approach altogether.

[Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/677311932092514343/heat_wave_ss_from_pzone.lua)

Reported 12/02/2020 by @pyrQ

**Comment by ahtelel** [comment]
If having `Heat Wave` check for original type would be wrong somehow, do comment.

**Comment by pyrQ** [comment]
Fixed here: https://github.com/ProjectIgnis/CardScripts/commit/3d1177f1941665699a3561ed98454c8abe2736f0 and https://github.com/ProjectIgnis/CardScripts/commit/b5793d20367c720156e4ae618afb04b69bf76207
Along with some other scenarios, like being unable to Special Summon a Fusion Monster from your Pendulum Zone after using the effect of "Elemental HERO Blazeman".

Only checking the original type breaks other scenarios involving Gemini Monsters, like not being able to Normal Summon them again or Special Summon them from the GY after using "Heat Wave", when you should be able to.
