### ISSUE TITLE
"Elemental HERO Magma Neos"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#203]
Ruling
> Q: When Elemental HERO Magma Neos returns to the Extra Deck by its own effect during the End Phase, its effect that returns all cards on the field to the hand activates. Can I chain Divine Wrath to this effect’s activation?
A: When the effect of Elemental HERO Magma Neos activates in the Extra Deck, you can chain Divine Wrath, in which case the effect’s activation is negated, but Elemental HERO Magma Neos is not destroyed.

Card is destroyed in Extra Deck.

[Puzzle](https://cdn.discordapp.com/attachments/281062530955345920/695280448535789618/magma_neos-divine_wrath.lua)

Reported 02/04/2020 by @pyrQ

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro-core/commit/c504ec57f71027aa0cec681f408bd5273a8c59e3
