### ISSUE TITLE
Returning control of Kaiju monsters via Owner's Seal

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#210]
If the player uses **Owner's Seal** to get control of a Kaiju that he summoned to the opponent's via the Kaiju's procedure, the game prompts the player to choose what Kaiju to send to the gy, which is incorrect: the Kaiju that got control changed should be the one to the sent to the GY.
Also, it is even possible to send both Kaiju monsters you control to the GY, by selecting the two of them.

Setup puzzle:
```
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(9720537,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(29726552,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(93332803,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(72167543,1,1,LOCATION_MZONE,3,1,true)
Debug.AddCard(9720537,1,1,LOCATION_MZONE,3,POS_FACEUP_ATTACK)
Debug.AddCard(36956512,0,0,LOCATION_MZONE,4,1,true)
Debug.ReloadFieldEnd()
```

**Comment by kevinlul** [comment]
Might be related to edo9300/ygopro-core#106
