### ISSUE TITLE
"Starving Venom Fusion Dragon" fails to proc its destruction effect

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#231]
[Turn 3](https://cdn.discordapp.com/attachments/291708361752313866/703586487576297542/Starving_Venom_Effect.yrpX)

Reported by @NaimSantos 25/04/2020

**Comment by NaimSantos** [comment]
Debugging the script says that all conditions to trigger the effect were met. It's probably the user choosing not to use the effect
