### ISSUE TITLE
Update Abyss Invitation

### ISSUE THREAD

**Issue by daneinator** [ProjectIgnis/CardScripts#284]
[c511009613.zip](https://github.com/ProjectIgnis/CardScripts/files/4801273/c511009613.zip)
I need help fixing     Duel.SetTargetPlayer(1-tp)
    Duel.SetTargetParam(200)
    Duel.SetOperationInfo(0,CATEGORY_DAMAGE,nil,0,1-tp,200)

**Comment by kevinlul** [comment]
Please explain what the problem is.

**Comment by daneinator** [comment]
> Please explain what the problem is.

Whenever an effect deals 500 or less damage, except Abyss Invitation, it deals 200 damage to your opponent. But for some reason, it doesn't respond to it.

**Comment by NaimSantos** [comment]
What doesn't respond? What is the "it"?

**Comment by daneinator** [comment]
> What doesn't respond? What is the "it"

For example, Say that cards like Hinotama deals you 500 points of damage, right? So, originally Abyss Invitation would take effect whenever one of the players takes effect damage. But it doesn't take effect after the effect damage is done.

**Comment by NaimSantos** [comment]
[Here is a replay demonstratring that Abyss Invitation is working properly.](https://cdn.discordapp.com/attachments/177100128874790923/724558627691823124/Abyss_Invitation_inflicting_damage.yrpX)

**Comment by daneinator** [comment]
What I meant to say was that it doesn't activate when you take damage from an opponent's effect damage.
