### ISSUE TITLE
Qliphort monsters not reducing their Levels after being Pendulum Summoned

### ISSUE THREAD

**Issue by ahtelel** [ProjectIgnis/CardScripts#299]
Qliphort monsters (and `Kaiser Sea Snake`)' levels are reduced if they are Special Summoned in any way except Pendulum Summon, which causes them to not be reduced.
[Associated puzzle.](https://cdn.discordapp.com/attachments/705211943031537704/728432438493052938/Qli.lua) Here, you can choose to Special Summon `Qliphort Stealth` with the effect of `Machina Armored Unit`, or by Pendulum Summoning.
Originally reported by @NaimSantos on 3/7/2020

**Comment by kevinlul** [comment]
This regression has been fixed with edo9300/ygopro-core@7adf8068f0d0b939132d8901c22c8b81130eb2ad
