### ISSUE TITLE
"Trishula, the Dragon of Icy Imprisonment" incorrectly activates its on-summon effect when summoned from the Graveyard

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#329]
[Turn 3](https://cdn.discordapp.com/attachments/184324960842416129/732681298434588762/fusion_trish_bug.yrpX). The Trishula in question was originally summoned with three Dragons and went to the Graveyard by becoming detached Xyz material. Its summon material is not resetting.

Reported July 14 by @NaimSantos

**Comment by pyrQ** [comment]
Fixed in https://github.com/ProjectIgnis/CardScripts/commit/e65eb22ddb418574af500b35eb281aa914f0b0fb
