### ISSUE TITLE
Monster stolen by "Borreload Dragon" can be returned to the opponent before being forced to the Graveyard

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#331]
[Puzzle](https://cdn.discordapp.com/attachments/705225331543506965/734605263415541780/BorreloadReturn.lua)

Reported July 3

**Comment by NaimSantos** [comment]
It was reverted to its previous state in https://github.com/ProjectIgnis/CardScripts/commit/fb76d65b02b472eb6348b6fd1803c246faedf680, which makes this invalid

**Comment by kevinlul** [comment]
fb76d65b02b472eb6348b6fd1803c246faedf680 reverts f284c244cd2d03f5de1eaf61f718e4fa7e66ef41, which resolves this issue, but f284c244cd2d03f5de1eaf61f718e4fa7e66ef41 was meant to fix #202. Thus there is a regression in that issue that will need to be investigated further.
