### ISSUE TITLE
"Predaplant Verte Anaconda" incorrectly allowed to copy "Fossil Fusion", "Dark Fusion", and similar cards

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#332]
[Puzzle](https://cdn.discordapp.com/attachments/705222140609298483/727907397506564126/Teste_Dark_Fusion_and_similars.lua)

Ruling
> Q. Is it possible to fuse and summon "E-HERO Inferno Wing", sending "Dark Fusion" from the deck to the graveyard by the effect of "②" of "Predatory Plant Verte Anaconda"?

> A. You cannot Fusion Summon "E-HERO Inferno Wing" by the method in question.

[Reported](https://discordapp.com/channels/705211942574227528/705222140609298483/727910703654240307) July 1 by @NaimSantos

**Comment by NaimSantos** [comment]
Fixed in https://github.com/ProjectIgnis/CardScripts/commit/e1778545175138a5df5c27755a75360c0fd9a65e
