### ISSUE TITLE
"Cynet Codec" incorrectly permitting targeting an already-summoned monster

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#333]
Steps for reproduction

1. Use "Recoded Alive" to summon "Code Talker". Resolve "Cynet Codec".
2. Pass to the opponent and activate "Recoded Alive" to summon "Code Talker Inverted"
3. Observe that "Code Talker" can be targeted, which is incorrect.

The error condition appears to be a Special Summon from the Extra Deck performed as part of a Chain.

[Puzzle by @edo9300 July 6](https://cdn.discordapp.com/attachments/705222140609298483/729657426844057680/01.lua), originally reported July 5 by @NaimSantos

**Comment by NaimSantos** [comment]
Fixed in #405
