### ISSUE TITLE
Should be allowed to use "Cosmic Flare" to substitute "Stardust Dragon" even under "Mask of Restrict"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#337]
[Puzzle by @NaimSantos](https://cdn.discordapp.com/attachments/705222140609298483/731815918749089864/Teste_Stardust_Cosmic_Flare_Mask_of_Restrict.lua)

See also Fluorohydride/ygopro#2311

**Comment by pyrQ** [comment]
Already handled with "Auxiliary.CostWithReplace".
