### ISSUE TITLE
Use SelectUnselect

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#4]
Originally opened April 26 by @AlphaKretin 

There are a variety of old cards that could be improved with SelectUnselect. For example, any card that uses multiple cards as a cost for a cancellable summon, like Block Dragon, cards that select multiple cards with the same or different properties, or cards that select cards with a total property up to a certain amount, like the second effect of Dried Winds. It will be difficult to find all of these, but seeking out a good number of somewhat popular cards is better than nothing.
- [x] ABC-Dragon Buster
- [x] All Level 2 Krawlers
- [x] Speedburst Dragon
- [x] The Sanctum of Parshath
- [x] Time Thief Regulator
- [x] Abyss Playhouse - Fantastic Theater
- [x] Spell Gear
- [x] Super Soldier Synthesis

These too
https://github.com/Fluorohydride/ygopro-scripts/pull/1251/files
https://github.com/Fluorohydride/ygopro-scripts/pull/1252/files

**Comment by AlphaKretin** [comment]
Dark Simorgh doesn't fit any suggested search pattern and could also stand to be updated

**Comment by kevinlul** [comment]
Closed again in bffd6fcca9fad0920823d3119581e53b2ab057b7
