### ISSUE TITLE
Monster Gate/Reasoning under Knightmare Corruptor Iblee

### ISSUE THREAD

**Issue by AlphaKretin** [ProjectIgnis/CardScripts#46]
This bug is also in YGOPro Percy.

When Knightmare Corruptor Iblee is on the field, you should not be able to activate Monster Gate or Reasoning as you cannot possibly summon a Link Monster from the Main Deck. However, their scripts only check that you can Special Summon, and Iblee's Special Summon lock not applying to everything makes that return true.

Has an associated puzzle.

**Comment by kevinlul** [comment]
Closed in 1f6bfbc5c02187181798011c159afb772909f7b0
