### ISSUE TITLE
Gussari @Ignister

### ISSUE THREAD

**Issue by duongnamphuong** [ProjectIgnis/CardScripts#494]
My "Gussari @Ignister" prompted me to activate its effect when **an opponent's** Link Monster destroys my monster by battle. It dealt damage to my opponent with the ATK of my destroyed monster.

Please see this replay, at the 5th turn.
[Gussari bug.zip](https://github.com/ProjectIgnis/CardScripts/files/5623310/Gussari.bug.zip)

I think its burn effect would only prompts to activate if **MY** Link monster destroys an opponent monster by battle.

**Comment by LogicalNonsense2051** [comment]
As stated from the About section of this repository:
```Send bug reports through Discord only! ```

Please follow the proper procedure for reporting bugs. I will be closing both this and the other issue that you have opened due to incorrect usage.
