### ISSUE TITLE
numbers evaille no longer works and causes a lot of errors

### ISSUE THREAD

**Issue by godpow** [ProjectIgnis/CardScripts#511]
![image](https://user-images.githubusercontent.com/17231911/102833527-593e4600-43bf-11eb-9d06-1991c490a898.png)

**Comment by lrhel** [comment]
As stated from the `About` section of this repository:
> Send bug reports through Discord only!

Please follow the proper procedure for reporting bugs. I will be closing this issue that you have opened due to incorrect usage.
