### ISSUE TITLE
The ID of Amazement Precious Park should be 33773528

### ISSUE THREAD

**Issue by mercury233** [ProjectIgnis/CardScripts#546]
https://github.com/ProjectIgnis/CardScripts/blob/LIOV-Official/official/c33773628.lua

![i-img1200x1200-1610939536meijhp9299](https://user-images.githubusercontent.com/13391795/106356707-830d5580-62f9-11eb-9830-f570ed90ff93.jpg)

**Comment by pyrQ** [comment]
Thanks for the report, fixed here:
https://github.com/ProjectIgnis/CardScripts/commit/691a1a15659d59c3f77f0241796173b440fe7875
https://github.com/ProjectIgnis/BabelCDB/commit/1555bc32e05ef5050c3975713801c53e53b641cd
