### ISSUE TITLE
The id of Zoha, Dreg of the Abhyss should be 35998832

### ISSUE THREAD

**Issue by mercury233** [ProjectIgnis/CardScripts#561]
![image](https://user-images.githubusercontent.com/13391795/110912887-5f7ff680-830c-11eb-8b18-ca1393d9a7ff.png)
https://github.com/ProjectIgnis/CardScripts/blob/master/official/c35998822.lua

**Comment by pyrQ** [comment]
Thanks, fixed here:
https://github.com/ProjectIgnis/CardScripts/commit/ec0e28c932a8cb0ba156fa256da30c779df8a7ee
https://github.com/ProjectIgnis/BabelCDB/commit/857cc4deb31735e8f33066a9d613ab93729c4016
