### ISSUE TITLE
EDOPRO xyz Import quick spell card bugs

### ISSUE THREAD

**Issue by xullul** [ProjectIgnis/CardScripts#612]
31/05/2021, I test a quick-play spell card name "XYZ Import" (14602126), it cannot activate during my turn, I have to set and activate during opponent turn only like a trap card. Hopefully this bug can be resolve soon. It's very cool xyz monster support card though.

**Comment by that-hatter** [comment]
1. As stated in https://github.com/ProjectIgnis/CardScripts#contributing, "Please keep all bug reports and questions on Discord; do NOT open an issue or pull request for this purpose."
2. The card works when I test it. All the more reason to provide further details in the Discord channel, along with a replay of it not working.
