### ISSUE TITLE
Ghostrick Doll force to chain effects during the End Phase

### ISSUE THREAD

**Issue by 7thSon85** [ProjectIgnis/CardScripts#623]
Hi
Recently I've come back playing some yugioh and I'm currently playing a pure Ghostrick, so not the best deck in history, but is a real fun... at least when this issue does not happen.
So, the problem is: when I flip G Doll, when her effects resolves during the end phase and I have "always chain" or "normal chain" settings (I didn't try with "ignore chain"), her effect force me to chain some other effects and I can't do anything to prevent (through a dialogue) or undo this chain. It could be useful to say that G Doll also autochain herself when she is flipped and I decide to activate some other effect first.
It wouldn't be so bad if it wasn't that I run "Needle Ceiling" in my deck!

Jks apart, what could be the issue?

**Comment by TheRazgriz** [comment]
Don't use the Ghub to report bugs. Make a report in the proper channel on Discord.
