### ISSUE TITLE
Enabling Edison Format

### ISSUE THREAD

**Issue by VetoPlayer** [ProjectIgnis/CardScripts#667]
Hello there!

I was wondering: is there any plan in the future to support Edison format?

**Comment by VetoPlayer** [comment]
If I were to develop a first patch set to support this feature, would ProjectIgnis accept it?

**Comment by pyrQ** [comment]
> If I were to develop a first patch set to support this feature, would ProjectIgnis accept it?

It would be reviewed and considered.
