### ISSUE TITLE
Souleating Oviraptor and Babycerasaurus swap

### ISSUE THREAD

**Issue by NikolaKeranovic** [ProjectIgnis/CardScripts#680]
When I pop the baby with second effect of Oviraptor for baby swap, baby that is on the field does not pop.
Only swap happens but effect of destroyed baby does not register.
Baby can be activated any number of times per turn, it is not restricted to pop amount.

**Comment by pyrQ** [comment]
1) Bug reports go to the Discord server with a replay attached.
2) Make sure that the Baby that you are reviving is NOT the same card that you destroyed. If you revive the same one then its effect cannot be activated (this has been the case ever since the April 2020 revisions).
