### ISSUE TITLE
Left Arm Offering can't activate with 3 other cards in hand

### ISSUE THREAD

**Issue by SibilantScream** [ProjectIgnis/CardScripts#725]
I think it's taking >3 rather than >2 as condition as it was activable before I had just set card from hand to the field.
![image](https://user-images.githubusercontent.com/61993103/169923459-53a66503-8174-4d85-9db4-7c514cf56d3b.png)

**Comment by pyrQ** [comment]
> You cannot Set Spells/Traps during the turn you activate this card.

This checks both before and after activating the card, meaning that if you Set a Spell/Trap from your hand then you can no longer activate "Left Arm Offering" in that same turn.

Also, in the future please use the relevant Discord channel on the Project Ignis Discord server for such inquiries.
