### ISSUE TITLE
The winged dragon of ra anime effect

### ISSUE THREAD

**Issue by Abbas-1998** [ProjectIgnis/CardScripts#746]
Hi,
I dont know if this article for this kind of question but I will ask after your permission of course,i have an issue with the divine beasts card the winged dragon of ra,slifer,obelisk,i am talking about the anime cards,they shouldnt be destroyed by battle unless with higher hierarchi-divine monster but the issue is this effect doesn't work and they are destroying,i hope you can fix it and good luck

**Comment by that-hatter** [comment]
From the README:
> Please keep all bug reports and questions on Discord; do NOT open an issue or pull request for this purpose.

Also, the anime versions of the god cards are not even in EDOPro, only the manga versions.
