### ISSUE TITLE
Egyptian divine beasts

### ISSUE THREAD

**Issue by Abbas-1998** [ProjectIgnis/CardScripts#747]
Hi
I have a problem with the Egyptian divine beasts(anime) some of their effect is not working like they shouldn't be destroyed by battle unless from higherarchi but this is not the case if you could fix the bug plz...

**Comment by pyrQ** [comment]
Anime gods aren't in-game, only manga ones. Yugi destroyed Obelisk with Silent Swordsman in the Ceremonial Duel. There are also other instances of this happening, for example in YGO:R.

You were already told to not do this here:
https://github.com/ProjectIgnis/CardScripts/issues/746

Thanks for straight-up ignoring what you were told, have a nice day.
