### ISSUE TITLE
Replace Auxiliary methods

### ISSUE THREAD

**Issue by NaimSantos** [ProjectIgnis/CardScripts#768]
The following auxiliary function should be renamed:

- [x] Auxiliary.AskAny                   -> Duel.AskAny
- [x] Auxiliary.AskEveryone              -> Duel.AskEveryone
- [x] Auxiliary.PlayFieldSpell           -> Duel.PlayFieldSpell
- [x] Auxiliary.SelectEffect             -> Duel.SelectEffect
- [x] Auxiliary.CheckPendulumZones       -> Duel.CheckPendulumZones
- [x] Auxiliary.AnnounceAnotherAttribute -> Duel.AnnounceAnotherAttribute
- [x] Auxiliary.AnnounceAnotherRace      -> Duel.AnnounceAnotherRace
- [x] Auxiliary.HasCounterListed -> Card.HasCounterListed
- [x] Auxiliary.CanPlaceCounter  -> Card.CanPlaceCounter
- [x] Auxiliary.nzatk            -> Card.HasNonZeroAttack
- [x] Auxiliary.nzdef            -> Card.HasNonZeroDefense
- [x] Auxiliary.disfilter1       -> Card.IsNegatableMonster
- [x] Auxiliary.disfilter2       -> Card.IsNegatableSpellTrap
- [x] Auxiliary.disfilter3       -> Card.IsNegatable
- [x] Auxiliary.IsMaterialListCode    -> Card.IsMaterialListCode
- [x] Auxiliary.IsMaterialListSetCard -> Card.IsMaterialListSetCard
- [x] Auxiliary.IsCodeListed          -> Card.IsCodeListed
- [x] Auxiliary.IsArchetypeCodeListed -> Card.IsArchetypeCodeListed
- [x] Auxiliary.IsCardTypeListed      -> Card.IsCardTypeListed
- [x] Auxiliary.HasListedSetCode      -> Card.HasListedSetCode

**Comment by that-hatter** [comment]
suggesting more descriptive names, and with more consistent casing:
 - Card.disfilter1 -> Card.IsNegatableMonster
 - Card.disfilter2 -> Card.IsNegatableSpellTrap
 - Card.disfilter3 -> Card.IsNegatable
 - Card.nzatk -> Card.HasNonZeroAttack
 - Card.nzdef -> Card.HasNonZeroDefense

**Comment by edo9300** [comment]
Tracked by https://github.com/ProjectIgnis/CardScripts/pull/779

**Comment by pyrQ** [comment]
"Duel.PlayFieldSpell" is specifically for activating a Field Spell so perhaps it should be renamed to "Duel.ActivateFieldSpell".
