### ISSUE TITLE
"Dark Sage" vs "Fire King Avatar Yaksha" (Trigger effects in the Deck)

### ISSUE THREAD

**Issue by pyrQ** [ProjectIgnis/CardScripts#97]
> Q.
If you have a "Dark Magician" on your field and destroy a "Fire King Avatar Yaksha" on the opponent's field with the effect of "Time Wizard", can you activate the effect of "Dark Sage" in your Deck as Chain Link 1 before the effect of the opponent's "Fire King Avatar Yaksha"?
A.
In this scenario, the opponent will decide whether to activate the effect of "Fire King Avatar Yaksha" first, so if it is activated, after it has been declared that the effect of "Fire King Avatar Yaksha" is activated, you can activate the effect of "Dark Sage" in the Deck.

>Q.
自分フィールドに「ブラック・マジシャン」がいて、「時の魔術師」の効果で相手フィールドの「炎王獣 ヤクシャ」を破壊した時、相手の「炎王獣ヤクシャ」の効果より先に自分のデッキにいる「黒衣の大賢者」の効果をチェーン①で発動できますか？
A.
ご質問の場合、相手が「炎王獣 ヤクシャ」の効果を先に発動するかしないかを決めることになりますので、発動するのであれば、「炎王獣 ヤクシャ」の効果の発動を宣言した後に、自分はデッキの「黒衣の大賢者」の効果を発動することができます。

This bug is present in both YGOPro Percy and EDOPro.

Currently in the above scenario the effect of "Dark Sage" is activated as Chain Link 1 while the effect of "Fire King Avatar Yaksha" is activated as Chain Link 2, when it should be the opposite. It seems like Trigger effects in the Deck don't follow the rules that Trigger effects in the hand do.

[Puzzle](https://cdn.discordapp.com/attachments/282741557797453825/663763832329601038/dark_sage_yaksha.lua)

**Comment by kevinlul** [comment]
Resolved with Fluorohydride/ygopro-core@973f3a6a83f4706b7abd9ce8763dc00caa7055b2 -> edo9300/ygopro-core@4cd2f0f777a78b076cfc6aa3a259685b40401641 (see also Fluorohydride/ygopro-core#1320
