### ISSUE TITLE
missing non over rush variant

### ISSUE THREAD

**Issue by marikisthar** [ProjectIgnis/CardScripts#994]
4 sets maximum cards from [https://yugipedia.com/wiki/Versus_Pack_Maximum_Force](url) are missing their standard (non over rush) cards variants, they are :

- Abyssal Dragon Lord Abyss Poseidra 
- Supreme Fullsteam Magnum Overlord 
- Abyssal Sea Dragon Abyss Kraken
- Shinesteel Ultra Dragon Devastar Okeabyss

and please switch thir ID's
- non over rush vaiants : 160207**0**XX
- over rush varians        : 160207**1**XX

and for next set this following cards may could have non ever rush variants :
- puresrass spears (160013033)
- wihel the mega monarch (160013018)
- estome the mega monarch (160013019)
- celeb rose luxury magicains (160013042)
- voidvelgr gigantomachia (160013040)
- charis magic - elegent change (160013052)
- nobody scat thief (160013060)

tnx in advance

**Comment by Yoshi80** [comment]
As there are no good-looking proxies for the non-Over Rush variants of those cards, these were not added. If you can find stuff that is to your liking, you can still replace images locally.
